/*
 * Created on 11 oct. 2017 ( Time 23:52:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.Gestion_Serveurs.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Persistent class for entity stored in table "server"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity @Data @NoArgsConstructor @AllArgsConstructor @ToString
@Table(name="server" )
public class Server implements Serializable{

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id")
    private Integer    id           ;

    @Column(name="libelle")
    private String     libelle      ;
    
    @Column(name="host")
    private String  host      ;
    
    @Column(name="login")
    private String login;
    
    @Column(name="password", length=255)
    private String password;

   
//    private Boolean    isDeleted    ;
    
    private String email;
    
    private String numero;
    
//    @ManyToOne
//    @JoinColumn(name="status_id", referencedColumnName="id")
//    private Statut statut      ;

///----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
